# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, choices=[('', '-- Select --'), ('NI', 'Nigeria'), ('US', 'United States'), ('IN', 'India')], max_length=3, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='%y/%m/%d')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_month', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('country', models.CharField(choices=[('', '-- Select --'), ('NI', 'Nigeria'), ('US', 'United States'), ('IN', 'India')], max_length=3)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, choices=[('', '-- Select --'), ('NI', 'Nigeria'), ('US', 'United States'), ('IN', 'India')], max_length=3, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='%y/%m/%d')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_experience', models.TextField(blank=True, null=True)),
                ('experience', models.ManyToManyField(to='common.Experience')),
                ('industry', models.ManyToManyField(to='common.Industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='experience',
            name='industry',
            field=models.ManyToManyField(to='common.Industry'),
        ),
        migrations.AddField(
            model_name='experience',
            name='languages_spoken',
            field=models.ManyToManyField(related_name='experience_language', to='common.Languages'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='experience',
            field=models.ManyToManyField(to='common.Experience'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='industry',
            field=models.ManyToManyField(to='common.Industry'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
