# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20171117_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='%y/%m/%d'),
        ),
    ]
