# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_experience_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='experience',
            field=models.ManyToManyField(blank=True, null=True, to='common.Experience'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='experience',
            field=models.ManyToManyField(blank=True, null=True, to='common.Experience'),
        ),
    ]
