# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0011_auto_20171206_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='files',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='coursegroupintermediate',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursegroupintermediate',
            name='group',
        ),
        migrations.RemoveField(
            model_name='course',
            name='groups',
        ),
        migrations.AddField(
            model_name='course',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.Files'),
        ),
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/course/logos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='course_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='messages',
            field=models.ManyToManyField(blank=True, to='common.Conversation'),
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, to='common.Videos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='uploads/course/files/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='uploads/course/video/%y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='CourseGroup',
        ),
        migrations.DeleteModel(
            name='CourseGroupIntermediate',
        ),
    ]
