# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0013_auto_20171207_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, choices=[('', '-- Select --'), ('NI', 'Nigeria'), ('US', 'United States'), ('IN', 'India')], max_length=3, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='%y/%m/%d')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agree_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='training',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='awarded_certificates',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='training',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='user',
        ),
        migrations.RenameField(
            model_name='entrepreneurprofile',
            old_name='about_me',
            new_name='professional_experience',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 8, 8, 5, 9, 920551, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.DeleteModel(
            name='UserTraining',
        ),
        migrations.AddField(
            model_name='profile',
            name='entreprenuer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.EntrepreneurProfile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.ManyToManyField(to='common.Industry'),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_spoken',
            field=models.ManyToManyField(to='common.Languages'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.MentorProfile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
