# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20171208_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
