# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20171208_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='industry',
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='industry',
            field=models.ManyToManyField(to='common.Industry'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='need_help',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='industry',
            field=models.ManyToManyField(to='common.Industry'),
        ),
    ]
