# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20171208_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='business_experience_country',
            field=models.CharField(blank=True, choices=[('', '-- Select --'), ('NI', 'Nigeria'), ('US', 'United States'), ('IN', 'India')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='company_role',
            field=models.CharField(default='ceo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='management_experience',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='ownership_experience',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_year',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('n', "I'd prefer not to share")], max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '-- Select --'), ('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('n', "I'd prefer not to share")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='professional_experience',
            field=models.TextField(blank=True, help_text='Explain about your professional experience!', null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='professional_experience',
            field=models.TextField(blank=True, help_text='Explain about your professional experience!', null=True),
        ),
    ]
