# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0019_auto_20171208_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/group/logos/%y/%m/%d')),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, to='common.Files')),
                ('industry', models.ManyToManyField(blank=True, to='common.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='GroupConversationIntermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Conversation')),
                ('files', models.ManyToManyField(blank=True, to='common.Files')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='files',
        ),
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
        migrations.RemoveField(
            model_name='course',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_year',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('n', "I'd prefer not to share"), ('2001', 2001), ('2000', 2000), ('1999', 1999), ('1998', 1998), ('1997', 1997), ('1996', 1996), ('1995', 1995), ('1994', 1994), ('1993', 1993), ('1992', 1992), ('1991', 1991), ('1990', 1990), ('1989', 1989), ('1988', 1988), ('1987', 1987), ('1986', 1986), ('1985', 1985), ('1984', 1984), ('1983', 1983), ('1982', 1982), ('1981', 1981), ('1980', 1980), ('1979', 1979), ('1978', 1978), ('1977', 1977), ('1976', 1976), ('1975', 1975), ('1974', 1974), ('1973', 1973), ('1972', 1972), ('1971', 1971), ('1970', 1970), ('1969', 1969), ('1968', 1968), ('1967', 1967), ('1966', 1966), ('1965', 1965), ('1964', 1964), ('1963', 1963), ('1962', 1962), ('1961', 1961), ('1960', 1960), ('1959', 1959), ('1958', 1958), ('1957', 1957), ('1956', 1956), ('1955', 1955), ('1954', 1954), ('1953', 1953), ('1952', 1952), ('1951', 1951), ('1950', 1950), ('1949', 1949), ('1948', 1948), ('1947', 1947), ('1946', 1946), ('1945', 1945), ('1944', 1944), ('1943', 1943), ('1942', 1942), ('1941', 1941), ('1940', 1940), ('1939', 1939), ('1938', 1938), ('1937', 1937)], max_length=4),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='common.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(blank=True, through='common.GroupConversationIntermediate', to='common.Conversation'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='videos',
            field=models.ManyToManyField(blank=True, to='common.Videos'),
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Profile'),
        ),
    ]
