# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_groupconversationintermediate_is_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupconversationintermediate',
            name='files',
        ),
        migrations.AddField(
            model_name='conversation',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.Files'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_type',
            field=models.CharField(choices=[('', '-- Select --'), ('group', 'Group')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
