# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20171221_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(related_name='course_teachers', to='common.Profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(blank=True, through='common.CourseInstructorProfile', to='common.Profile'),
        ),
    ]
