# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20171221_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='course_files', to='common.Files'),
        ),
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='course_videos', to='common.Videos'),
        ),
    ]
