# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20171221_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('', 'Select'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('invalid', 'Invalid'), ('auth', 'Auth')], default='', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Course')),
            ],
        ),
    ]
