# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20171221_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_year',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('n', "I'd prefer not to share"), ('2002', 2002), ('2001', 2001), ('2000', 2000), ('1999', 1999), ('1998', 1998), ('1997', 1997), ('1996', 1996), ('1995', 1995), ('1994', 1994), ('1993', 1993), ('1992', 1992), ('1991', 1991), ('1990', 1990), ('1989', 1989), ('1988', 1988), ('1987', 1987), ('1986', 1986), ('1985', 1985), ('1984', 1984), ('1983', 1983), ('1982', 1982), ('1981', 1981), ('1980', 1980), ('1979', 1979), ('1978', 1978), ('1977', 1977), ('1976', 1976), ('1975', 1975), ('1974', 1974), ('1973', 1973), ('1972', 1972), ('1971', 1971), ('1970', 1970), ('1969', 1969), ('1968', 1968), ('1967', 1967), ('1966', 1966), ('1965', 1965), ('1964', 1964), ('1963', 1963), ('1962', 1962), ('1961', 1961), ('1960', 1960), ('1959', 1959), ('1958', 1958), ('1957', 1957), ('1956', 1956), ('1955', 1955), ('1954', 1954), ('1953', 1953), ('1952', 1952), ('1951', 1951), ('1950', 1950), ('1949', 1949), ('1948', 1948), ('1947', 1947), ('1946', 1946), ('1945', 1945), ('1944', 1944), ('1943', 1943), ('1942', 1942), ('1941', 1941), ('1940', 1940), ('1939', 1939), ('1938', 1938)], max_length=4),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='expertise_areas',
            field=models.ManyToManyField(blank=True, related_name='expertise_areas_entrepreneurprofiles', to='common.ExpertiseAreas'),
        ),
    ]
