# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20180102_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='expert_areas',
            field=models.ManyToManyField(blank=True, related_name='expert_areas_entrepreneurprofiles', to='common.Industry'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='industry',
            field=models.ManyToManyField(related_name='industry_entrepreneurprofiles', to='common.Industry'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expert_areas',
            field=models.ManyToManyField(blank=True, related_name='expert_areas_mentorprofiles', to='common.Industry'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='industry',
            field=models.ManyToManyField(related_name='industry_mentorprofiles', to='common.Industry'),
        ),
    ]
