# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20180102_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
