# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_course_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('', '-- Select --'), ('running-business', 'Running a business'), ('starting-business', 'Starting a Business'), ('growing-business', 'Growing a business'), ('workshops-seminars', 'Workshops & Seminars'), ('interviews', 'Interviews')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
